### ISSUE TITLE
error loading demoApp

### ISSUE THREAD

**Issue by spike83** [reyesoft/ts-angular-jsonapi#10]
Hi,

I always get the error below when I run the application in browser:

Error: [$injector:nomod] Module 'Jsonapi.services' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.8/$injector/nomod?p0=Jsonapi.services

return new ErrorConstructor(message);

Thanks in advance,
Simon

**Comment by pablorsk** [comment]
You receive this message with the demo? Or just on your project?

If is in your project, you maybe fotget add ts-angular-jsonapi.js file.

Regards...

**Comment by spike83** [comment]
Yes this happens in my demoApp just cloned from master branch.

**Comment by pablorsk** [comment]
I try but is working. Please, can you try again in new folder?

```
git clone git@github.com:reyesoft/ts-angular-jsonapi.git
npm install
gulp serve
```

I try now, and work. If the problem persist, please, share all errors and steps.

**Comment by spike83** [comment]
Hi, I had a blank try in a tem folder.

These are the outputs of «npm install» and «gulp serve»:

D:\temp\jsonapi-test\ts-angular-jsonapi>npm install

npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.

npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> ts-angular-jsonapi@0.0.1 postinstall D:\temp\jsonapi-test\ts-angular-jsonapi
> 
> npm run typings install && gulp
> 
> ts-angular-jsonapi@0.0.1 typings D:\temp\jsonapi-test\ts-angular-jsonapi
> 
> typings "install"

├── angular (ambient)

├── angular-animate (ambient)

├── angular-route (ambient)

└── jquery (ambient)

(node:11700) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

[07:42:25] Using gulpfile D:\temp\jsonapi-test\ts-angular-jsonapi\gulpfile.js

[07:42:25] Starting 'dist'...

[07:42:28] Finished 'dist' after 2.89 s

[07:42:28] Starting 'default'...

[07:42:28] Finished 'default' after 19 µs

src\library_all.ts(1,1): error TS6053: File 'D:/temp/jsonapi-test/ts-angular-jsonapi/typings/main.d.ts' not found.

[07:42:28] TypeScript: 1 semantic error

[07:42:28] TypeScript: emit succeeded (with errors)

ts-angular-jsonapi@0.0.1 D:\temp\jsonapi-test\ts-angular-jsonapi

+-- browser-sync@2.13.0

| +-- browser-sync-client@2.4.2

… Skipped all the list of modules …

  +-- wordwrap@1.0.0

  `-- xtend@4.0.1

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:

npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

D:\temp\jsonapi-test\ts-angular-jsonapi>gulp serve

(node:7368) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

[09:04:08] Using gulpfile D:\temp\jsonapi-test\ts-angular-jsonapi\gulpfile.js

[09:04:08] Starting 'lib'...

[09:04:08] Starting 'demo'...

[09:04:08] Starting 'watch'...

[09:04:08] Finished 'watch' after 62 ms

[09:04:10] Finished 'demo' after 2.11 s

[09:04:11] Finished 'lib' after 2.92 s

[09:04:11] Starting 'serve'...

Starting browserSync and superstatic...

[09:04:11] Finished 'serve' after 62 ms

D:\temp\jsonapi-test\ts-angular-jsonapi>npm -version

3.8.8

D:\temp\jsonapi-test\ts-angular-jsonapi>gulp -v

[09:11:44] CLI version 1.2.2

[09:11:44] Local version 3.9.1

Serving on Window 10.

In the console (Firebug) I got the following messages:

Error: [$injector:nomod] Module 'Jsonapi.services' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument. http://errors.angularjs.org/1.4.8/$injector/nomod?p0=Jsonapi.services

return new ErrorConstructor(message);

angular.js (Zeile 68, Spalte 12)

Error: [$injector:nomod] Module 'demoApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument. http://errors.angularjs.org/1.4.8/$injector/nomod?p0=demoApp

return new ErrorConstructor(message);

angular.js (Zeile 68, Spalte 12)

Error: [$injector:modulerr] Failed to instantiate module demoApp due to: [$injector:nomod] Module 'demoApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument. http://errors.angularjs.org/1.4.8/$injector/nomod?p0=demoApp minErr/<@http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.js:68:12 module/<@http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.js:2005:17 ensure@http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.js:1929:38 module@http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.js:2003:14 loadModules/<@http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.js:4435:22 forEach@http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.js:340:11 loadModules@http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.js:4419:5 createInjector@http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.js:4344:11 bootstrap/doBootstrap@http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.js:1676:20 bootstrap@http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.js:1697:12 angularInit@http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.js:1591:5 @http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.js:29013:5 trigger@http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.js:3057:7 defaultHandlerWrapper@http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.js:3346:3 createEventHandler/eventHandler@http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.js:3334:9 http://errors.angularjs.org/1.4.8/$injector/modulerr?p0=demoApp&p1=%5B%24injector%3Anomod%5D%20Module%20'demoApp'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.4.8%2F%24injector%2Fnomod%3Fp0%3DdemoApp%0AminErr%2F%3C%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.8%2Fangular.js%3A68%3A12%0Amodule%2F%3C%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.8%2Fangular.js%3A2005%3A17%0Aensure%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.8%2Fangular.js%3A1929%3A38%0Amodule%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.8%2Fangular.js%3A2003%3A14%0AloadModules%2F%3C%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.8%2Fangular.js%3A4435%3A22%0AforEach%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.8%2Fangular.js%3A340%3A11%0AloadModules%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.8%2Fangular.js%3A4419%3A5%0AcreateInjector%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.8%2Fangular.js%3A4344%3A11%0Abootstrap%2FdoBootstrap%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.8%2Fangular.js%3A1676%3A20%0Abootstrap%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.8%2Fangular.js%3A1697%3A12%0AangularInit%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.8%2Fangular.js%3A1591%3A5%0A%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.8%2Fangular.js%3A29013%3A5%0Atrigger%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.8%2Fangular.js%3A3057%3A7%0AdefaultHandlerWrapper%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.8%2Fangular.js%3A3346%3A3%0AcreateEventHandler%2FeventHandler%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.8%2Fangular.js%3A3334%3A9%0A

return new ErrorConstructor(message);

Nothing was changed in source files:

D:\temp\jsonapi-test\ts-angular-jsonapi>git status

On branch master

Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:

  (use "git add <file>..." to update what will be committed)

  (use "git checkout -- <file>..." to discard changes in working directory)

```
    modified:   dist/ts-angular-jsonapi.js

    modified:   dist/ts-angular-jsonapi.min.js

    modified:   dist/tsd.d.ts
```

no changes added to commit (use "git add" and/or "git commit -a")

Best Regards

Simon

Von: Pablo Reyes [mailto:notifications@github.com] 
Gesendet: Dienstag, 26. Juli 2016 14:25
An: reyesoft/ts-angular-jsonapi ts-angular-jsonapi@noreply.github.com
Cc: Simon Hofer simon.hofer@sbnet.ch; Author author@noreply.github.com
Betreff: Re: [reyesoft/ts-angular-jsonapi] error loading demoApp (#10)

I try but is working. Please, can you try again in new folder?

git clone git@github.com:reyesoft/ts-angular-jsonapi.git mailto:git@github.com:reyesoft/ts-angular-jsonapi.git 
npm install
gulp serve

I try now, and work. If the problem persist, please, share all errors and steps.

**Comment by pablorsk** [comment]
Please, run

`npm install -g bower gulp typings`

I'm fixing readme for future confusions....

**Comment by pablorsk** [comment]
Also, and now, you can update reposotory. I add a some of features and lines for prevet this type of errors.

#11

**Comment by pablorsk** [comment]
I open again the ticket, becouse the problem is in windows...

The problem is GULP on `lib` task. This task return a `ts-angular-jsonapi.js` in windows and another version on `linux`, with another sort.

**Comment by pablorsk** [comment]
Problem solved on Windows @spike83 ! :)

``` bash
git clone git@github.com:reyesoft/ts-angular-jsonapi.git
cd ts-angular-jsonapi
npm install -g gulp typings
npm run demoinstall
gulp serve
```
