### ISSUE TITLE
'ts-angular-jsonapi' is not in the npm registry.

### ISSUE THREAD

**Issue by dadakoko** [reyesoft/ts-angular-jsonapi#7]
hi 
i can not install the module using npm install ts-angular-jsonapi --save,

any idea?
thanks

**Comment by pablorsk** [comment]
wait please....

**Comment by pablorsk** [comment]
Please, try again and enjoy! :P

```
npm install ts-angular-jsonapi --save
```

**Comment by dadakoko** [comment]
ok done! it appears in my node_modules...
thanks for your fast reply:-)
